#!/usr/bin/env python3
"""字幕处理（Phase 1）—— 句级 SRT 的后期整理，适配手机竖屏可读性。

- ticks_to_seconds：Edge TTS 时间轴单位为 100 纳秒 tick，转秒（供测试/复用）。
- wrap_srt_lines：把过长字幕句按字数折行（中文无空格，按字符切），避免单行溢出。
"""

import re
from pathlib import Path

_TICKS_PER_SECOND = 10_000_000  # 100 纳秒 = 1 tick


def ticks_to_seconds(ticks):
    """Edge TTS offset/duration 单位换算：100ns tick → 秒。"""
    return ticks / _TICKS_PER_SECOND


def _parse_srt(srt_text):
    """极简 SRT 解析 → list of (index, start, end, content)。"""
    blocks = re.split(r"\r?\n\r?\n", srt_text.strip())
    out = []
    tc_re = re.compile(
        r"(\d{2}):(\d{2}):(\d{2}),(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2}),(\d{3})"
    )
    for blk in blocks:
        lines = [l for l in blk.splitlines() if l.strip() != ""]
        if not lines:
            continue
        # 找时间轴行
        tcm = None
        idx = None
        for i, ln in enumerate(lines):
            m = tc_re.search(ln)
            if m:
                tcm = m
                if i > 0 and lines[i - 1].strip().isdigit():
                    idx = int(lines[i - 1].strip())
                content = "\n".join(lines[i + 1:])
                break
        if not tcm:
            continue
        out.append((idx, tcm, content))
    return out


def _wrap_text(text, max_chars):
    """把一段文字按 max_chars 折行（中文按字符切，英文尽量按词）。"""
    text = text.strip()
    if not text:
        return text
    # 先按已有换行拆，再对超长行切分
    lines = []
    for raw in text.split("\n"):
        raw = raw.strip()
        if len(raw) <= max_chars:
            lines.append(raw)
            continue
        # 英文优先按空格切，中文退化为按字符
        if re.search(r"[A-Za-z]", raw) and " " in raw:
            words = raw.split(" ")
            cur = ""
            for w in words:
                if cur and len(cur) + len(w) + 1 > max_chars:
                    lines.append(cur)
                    cur = w
                else:
                    cur = (cur + " " + w) if cur else w
            if cur:
                lines.append(cur)
        else:
            for i in range(0, len(raw), max_chars):
                lines.append(raw[i:i + max_chars])
    return "\n".join(lines)


def wrap_srt_lines(srt_text, max_chars=18):
    """对 SRT 每条字幕内容做字数折行，返回处理后的 SRT 文本。"""
    cues = _parse_srt(srt_text)
    out = []
    for i, (idx, tcm, content) in enumerate(cues, start=1):
        wrapped = _wrap_text(content, max_chars)
        out.append(f"{i}\n{tcm.group(0)}\n{wrapped}")
    return "\n\n".join(out) + ("\n" if out else "")


def postprocess(srt_path, max_chars=18):
    """就地优化字幕文件（折行）。返回 Path。"""
    p = Path(srt_path)
    if not p.exists():
        return p
    text = p.read_text(encoding="utf-8")
    wrapped = wrap_srt_lines(text, max_chars=max_chars)
    p.write_text(wrapped, encoding="utf-8")
    return p


def _ass_color(v, default="&H00FFFFFF"):
    """'0xRRGGBB' / '0xAARRGGBB' → ASS 的 '&HAABBGGRR'（注意 ASS 是 BGR 序）。"""
    if v is None:
        return default
    s = str(v).strip()
    if s.lower().startswith("0x"):
        s = s[2:]
    s = s.upper()
    if len(s) == 8:  # AARRGGBB
        aa, rr, gg, bb = s[0:2], s[2:4], s[4:6], s[6:8]
    elif len(s) == 6:  # RRGGBB
        aa, rr, gg, bb = "00", s[0:2], s[2:4], s[4:6]
    else:
        return default
    return f"&H{aa}{bb}{gg}{rr}"


def _fmt_ass_time(h, m, s, ms):
    """SRT 时间 → ASS 时间 'H:MM:SS.cc'（厘秒）。"""
    return f"{int(h)}:{int(m):02d}:{int(s):02d}.{int(ms) // 10:02d}"


def srt_to_ass(srt_text, *, width=1080, height=1920, font_size=46,
               primary_color="0xFFFFFF", outline_color="0x000000",
               back_color="0x80000000", outline=4, margin_v=140,
               margin_h=60, font_name="Arial"):
    """把 SRT 转成带正确 PlayRes 的 ASS。

    关键：ffmpeg 的 subtitles 滤镜对 SRT 会把 PlayRes 固定为 384x288，
    导致 FontSize/MarginV 被按 288 缩放（在 1080x1920 上放大 ~6.7 倍、跑到画面中部）。
    original_size 选项在部分构建下无效。这里自行生成 PlayRes=视频尺寸 的 ASS，
    让字号/边距/位置按真实像素解释，彻底规避该坑。

    Args:
        srt_text: 已折行的 SRT 文本。
        width/height: 视频尺寸（写入 PlayResX/Y）。
        font_size: 字号（真实像素）。
        *_color: '0xRRGGBB' 或 '0xAARRGGBB'。
        outline: 描边宽度。margin_v: 距底边像素。margin_h: 左右留白像素。
    Returns:
        str: ASS 文本。
    """
    cues = _parse_srt(srt_text)
    primary = _ass_color(primary_color, "&H00FFFFFF")
    outline_c = _ass_color(outline_color, "&H00000000")
    back = _ass_color(back_color, "&H80000000")
    header = [
        "[Script Info]",
        "; Generated by video_pipeline.subtitles.srt_to_ass",
        "ScriptType: v4.00+",
        f"PlayResX: {int(width)}",
        f"PlayResY: {int(height)}",
        "ScaledBorderAndShadow: yes",
        "WrapStyle: 2",
        "YCbCr Matrix: None",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, "
        "ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, "
        "MarginL, MarginR, MarginV, Encoding",
        f"Style: Default,{font_name},{int(font_size)},{primary},{primary},"
        f"{outline_c},{back},0,0,0,0,100,100,0,0,1,{int(outline)},0,2,"
        f"{int(margin_h)},{int(margin_h)},{int(margin_v)},1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    body = []
    for _, tcm, content in cues:
        h1, m1, s1, ms1, h2, m2, s2, ms2 = (int(g) for g in tcm.groups())
        start = _fmt_ass_time(h1, m1, s1, ms1)
        end = _fmt_ass_time(h2, m2, s2, ms2)
        text = content.replace("\n", "\\N")
        body.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}")
    return "\n".join(header + body) + "\n"


def parse_segments(srt_text):
    """把 SRT 解析为句时间轴 list[{"start","end","text"}]（秒），供剪接对齐。

    兼容句级/逐词 SRT；多行内容合并为一句。无效块跳过。
    """
    def _to_sec(tc, off):
        return (int(tc.group(off)) * 3600 + int(tc.group(off + 1)) * 60 +
                int(tc.group(off + 2)) + int(tc.group(off + 3)) / 1000.0)
    segs = []
    for _idx, tcm, content in _parse_srt(srt_text):
        start = _to_sec(tcm, 1)
        end = _to_sec(tcm, 5)
        text = " ".join(content.split())
        if end > start:
            segs.append({"start": start, "end": end, "text": text})
    return segs
